baseURL = "https://scharitzer.io"
languageCode = "en-us"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true



[params]
  author = "Markus Scharitzer"
  description = "In solitude, where we are least alone."
  github = "droptableuser"
  twitter = "droptableuser"
  linkedin = "markus-scharitzer"
  twitch = "droptableuser"
  email = "markus@scharitzer.io"
  url = "https://scharitzer.io"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  favicon = "/images/github.png"
  location = "Austria"
  userStatusEmoji = "😀"
  enableGitalk = false
  avatar="./images/markus.png"


[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
